# Matrix and Cumulative Sum in Numpy Array

Numpy provides another class in addition to arrays: that's matrix.The matrix class is subclass of the ndarray and is basically identical to the ndarray with one notable exception: the ndarray object are high dimensional array where in **matrix object are strictly 2 dimensional**.

## Implementation:

```import numpy as np
mat=np.matrix([[1,2],[3,4]])
print(mat)```

In [3]:
import numpy as np
mat=np.matrix([[1,2],[3,4]])
print(mat,type(mat),mat.shape,mat.ndim)

[[1 2]
 [3 4]] <class 'numpy.matrix'> (2, 2) 2


**We can also convert Numpy array to matrix using asmatrix() function.**

In [12]:
arr=np.array(range(0,8)).reshape(2,4)
print("Array:\n",arr,"\n\nShape:",arr.shape,"\n\nType:",type(arr))
#converting to matrix type
mat=np.asmatrix(arr)
print("\nAfter Updating:",type(mat))

Array:
 [[0 1 2 3]
 [4 5 6 7]] 

Shape: (2, 4) 

Type: <class 'numpy.ndarray'>

After Updating: <class 'numpy.matrix'>


**Another important point about ndarray and matrix class is :
On multiplying two ndarray - element wise multiplication happens
while for matrix - its equivalent to dot product of two array.**

In [18]:
arr=np.array(range(1,5)).reshape(2,2)
arr1=arr*arr
mat=np.asmatrix(arr)
mat1=mat*mat #same as dot product of array
mat2=np.dot(arr,arr)
print(f"\n\n{arr1}\n\n{mat1}\n\n{mat2}")



[[ 1  4]
 [ 9 16]]

[[ 7 10]
 [15 22]]

[[ 7 10]
 [15 22]]


### Cumulative sum

Very often while numerical operation there will be a need to calculate cumulative sum of Numpy arrays.We can call cumsum() function to get the cumulative sum of array elements.

Note:
* we can pass axis=0 to get cumulative sum of column elements
* axis=1 for row elements

In [22]:
arr=np.array(range(0,12)).reshape(2,3,2)
Casum=np.cumsum(arr)
print(arr,"\n",Casum)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 
 [ 0  1  3  6 10 15 21 28 36 45 55 66]


In [24]:
csum=np.cumsum(arr,axis=0)
print(arr,"\n\n",csum)

[[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  7]
  [ 8  9]
  [10 11]]] 

 [[[ 0  1]
  [ 2  3]
  [ 4  5]]

 [[ 6  8]
  [10 12]
  [14 16]]]


In [25]:
rsum=np.cumsum(arr,axis=1)
rsum

array([[[ 0,  1],
        [ 2,  4],
        [ 6,  9]],

       [[ 6,  7],
        [14, 16],
        [24, 27]]], dtype=int32)