# Numpy Sorting

We can use sort() function to sort numpy arrays.


In [10]:
import numpy as np
arr=np.array([2,7,3,4,9,0,1,10,3]).reshape(3,-1)
arr1=np.sort(arr)
print("\nOriginal Array\n\n",arr)
print("Sorted Array\n\n",arr1)



Original Array

 [[ 2  7  3]
 [ 4  9  0]
 [ 1 10  3]]
Sorted Array

 [[ 2  3  7]
 [ 0  4  9]
 [ 1  3 10]]


In [11]:
#to sort array inplace do as follows:
arr.sort()
arr

array([[ 2,  3,  7],
       [ 0,  4,  9],
       [ 1,  3, 10]])

* **argsort()** - returns index of sorted array.

In [73]:
np.random.seed(10)
arr=np.random.randint(2,90,(3,4))
indx=arr.argsort()
print(arr,"\n\n sorted index:\n\n",indx,"\n\nReversed index:\n",indx[:,::-1])
print("\n",arr[0][indx[0]])


[[11 17 66 30]
 [31 10 75  2]
 [42 38 18 13]] 

 sorted index:

 [[0 1 3 2]
 [3 1 0 2]
 [3 2 1 0]] 

Reversed index:
 [[2 3 1 0]
 [2 0 1 3]
 [0 1 2 3]]

 [11 17 30 66]


In [66]:
np.random.seed(27)
height=np.random.randint(150,200,6)
weight=np.random.randint(45,89,6)
names=np.array(['a',"b",'c','d','e','f'])
sortedin=weight.argsort()
print(weight,height,names)
print(names[sortedin])
print(weight[sortedin])
print(height[sortedin])


[70 58 47 87 78 55] [169 158 181 198 187 174] ['a' 'b' 'c' 'd' 'e' 'f']
['c' 'f' 'b' 'a' 'e' 'd']
[47 55 58 70 78 87]
[181 174 158 169 187 198]
