# Numpy Array Indexing

1. Numpy indexing is same as accessing numpy array.
2. We can access numpy array elements refering Index and Boolean Index.
3. Array index begins from 0 i.e first element is at position/index 0.

## Implemention

### 1-D array:

In [161]:
*list1,=1,2,3,4,5
print(f"List:{list1},Type:{type(list1)}")

List:[1, 2, 3, 4, 5],Type:<class 'list'>


In [162]:
import numpy as np
arr=np.array(list1)
print(f"Dimensions:{arr.ndim} ; Array Shape:{arr.shape}")
print(arr) 
print(arr[0])##accessing first element;passing index
print("Passing list of index to array:",arr[[0,2]]) #passing list of index

Dimensions:1 ; Array Shape:(5,)
[1 2 3 4 5]
1
Passing list of index to array: [1 3]


### 2-D array:

In [163]:
arr=np.array(list1,ndmin=2)
print(f"Dimensions:{arr.ndim} ; Array Shape:{arr.shape}")
print(arr,"\n",arr[0,2],"\n",arr[0][1]) #passing index to access array
print("Passing list of index to array:",arr[0][[2,3]])

Dimensions:2 ; Array Shape:(1, 5)
[[1 2 3 4 5]] 
 3 
 2
Passing list of index to array: [3 4]


### 3-D array :

In [164]:
arr=np.array([[[1,2,3],[2,4,5]],[[2,3,4],[4,5,6]]])
print(f"Dimensions:{arr.ndim} ; Array Shape:{arr.shape}")
print(arr,"\n",arr[0,1,2],"\n",arr[0][1][2]) #passing index to access array
print("Passing list of index to array:",arr[1][1][[1,2]])

Dimensions:3 ; Array Shape:(2, 2, 3)
[[[1 2 3]
  [2 4 5]]

 [[2 3 4]
  [4 5 6]]] 
 5 
 5
Passing list of index to array: [5 6]


## Boolean Indexing

In [165]:
arr=np.array(list1)
print(arr)
print(arr%2==1) # will go through each element and returns list of boolean values.
arr[arr%2==1]  #list of boolean values is feeded as index;Boolean indexing.

[1 2 3 4 5]
[ True False  True False  True]


array([1, 3, 5])

In [166]:
arr=np.array([[[1,2,3],[2,4,5]],[[2,3,4],[4,5,6]]])
print(f"Dimensions:{arr.ndim} ; Array Shape:{arr.shape}")
print(arr)
print(arr%2==0)
print("Passing Boolean Indexing",arr[arr%2==0])#passing boolean index


Dimensions:3 ; Array Shape:(2, 2, 3)
[[[1 2 3]
  [2 4 5]]

 [[2 3 4]
  [4 5 6]]]
[[[False  True False]
  [ True  True False]]

 [[ True False  True]
  [ True False  True]]]
Passing Boolean Indexing [2 2 4 2 4 4 6]


# Nump Array Slicing

Slicing means taking elements from one given index to another given index.

**Syntax**
1. Instead of index we can pass slice ike this- [start:end:steps]
*By default start is 0, end is length of array,step is 1.*

In [167]:
list2=[6,7,8,9,10]
arr=np.array(list1)
print(arr)
print("Sliced array:",arr[1:4:3])
print("Sliced array with steps:",arr[::2])
print("Negative Indexing:",arr[-3:-1])

[1 2 3 4 5]
Sliced array: [2]
Sliced array with steps: [1 3 5]
Negative Indexing: [3 4]


In [168]:
list2=[6,7,8,9,10]
arr=np.array([list1,list2],ndmin=3)
print(arr)
print("Sliced array with steps:\n",arr[:,:,:3:2])
print("Sliced array:",arr[:,:,2:])

[[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
Sliced array with steps:
 [[[1 3]
  [6 8]]]
Sliced array: [[[ 3  4  5]
  [ 8  9 10]]]


### Refrencing and Slicing

In [169]:
arr1=arr[:,:,1::2] #arr1 is pointing/refrencing to arr,i.e any changes to anyone of the array will reflect in other.
print("array1:",arr1,"\nDimensions:",arr1.ndim,"\tSliced Array Shape:",arr1.shape,"\tOriginal array shape:",arr.shape)

array1: [[[2 4]
  [7 9]]] 
Dimensions: 3 	Sliced Array Shape: (1, 2, 2) 	Original array shape: (1, 2, 5)


In [170]:
print("Before changes",arr)
arr1[0,1,0]=90
print("Updated:",arr)

Before changes [[[ 1  2  3  4  5]
  [ 6  7  8  9 10]]]
Updated: [[[ 1  2  3  4  5]
  [ 6 90  8  9 10]]]
