# Numpy Array Iteration

Iteration means going through elements one by one.As we deal with multidimensional array in numpy, we can do this with python for loop.For 1-D array by using for loop we can go through elements one b one.

In [2]:
import numpy as np
arr=np.array(range(10,20))
for i in arr[:-1]:
    print(i,end='-->')
print(arr[-1])

10-->11-->12-->13-->14-->15-->16-->17-->18-->19


In [9]:
#for high dimensional arrays it difficult to access elements by for loop.
import numpy as np
arr=np.array(range(10,90),ndmin=5).reshape(2,-1,4)
for i in arr[:-1]:
    print(i,end='\n')
print(arr[-1])


[[10 11 12 13]
 [14 15 16 17]
 [18 19 20 21]
 [22 23 24 25]
 [26 27 28 29]
 [30 31 32 33]
 [34 35 36 37]
 [38 39 40 41]
 [42 43 44 45]
 [46 47 48 49]]
[[50 51 52 53]
 [54 55 56 57]
 [58 59 60 61]
 [62 63 64 65]
 [66 67 68 69]
 [70 71 72 73]
 [74 75 76 77]
 [78 79 80 81]
 [82 83 84 85]
 [86 87 88 89]]


**As number of dimensions increase accessing elements using for loop becomes inconvinient as we need to iterate to each dimension to finally get elements**

Iteration using **nditer()**: The function nditer is a helping function that can be used for basic to advanced iteration.

In [12]:
#print(arr)
for i in np.nditer(arr):
    print(i,end=" ")

10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 

We can pass argument like:
* op_dtype: use this argument and pass expected datatype to change data type of elements while iterating.
* flags=['buffered] : numpy dont change data type of elements inplace , fo rthat we need extra space known as buffer and in order to enable it in nditer() we pass this argument.

In [13]:
for i in np.nditer(arr,flags=["buffered"],op_dtypes=["S"]):
    print(i,end=" ")

b'10' b'11' b'12' b'13' b'14' b'15' b'16' b'17' b'18' b'19' b'20' b'21' b'22' b'23' b'24' b'25' b'26' b'27' b'28' b'29' b'30' b'31' b'32' b'33' b'34' b'35' b'36' b'37' b'38' b'39' b'40' b'41' b'42' b'43' b'44' b'45' b'46' b'47' b'48' b'49' b'50' b'51' b'52' b'53' b'54' b'55' b'56' b'57' b'58' b'59' b'60' b'61' b'62' b'63' b'64' b'65' b'66' b'67' b'68' b'69' b'70' b'71' b'72' b'73' b'74' b'75' b'76' b'77' b'78' b'79' b'80' b'81' b'82' b'83' b'84' b'85' b'86' b'87' b'88' b'89' 

## Iterating with Different Step Size

In [16]:
for i in np.nditer(arr[:,:,::3],flags=["buffered"],op_dtypes=["S"]):
    print(i,end=" ")

b'10' b'13' b'14' b'17' b'18' b'21' b'22' b'25' b'26' b'29' b'30' b'33' b'34' b'37' b'38' b'41' b'42' b'45' b'46' b'49' b'50' b'53' b'54' b'57' b'58' b'61' b'62' b'65' b'66' b'69' b'70' b'73' b'74' b'77' b'78' b'81' b'82' b'85' b'86' b'89' 

## Enumerate using ndenumerate()

Enumerate means mentioning sequence of something one by one.

Sometimes we need index of element while iterating we can use ndenumerate in that case.

In [29]:
for id,x in np.ndenumerate(arr[:,::2,::5]):
    print(id,x,end="\n")

(0, 0, 0) 10
(0, 1, 0) 18
(0, 2, 0) 26
(0, 3, 0) 34
(0, 4, 0) 42
(1, 0, 0) 50
(1, 1, 0) 58
(1, 2, 0) 66
(1, 3, 0) 74
(1, 4, 0) 82
