# Numpy Searching Array

We can search an array for a certain value and return index if we get a value.We can search for array elements using
**where()** function.

In [3]:
import numpy as np
arr=np.array(range(1,10))
print(np.where(arr==5))

(array([4], dtype=int64),)


In [4]:
arr=np.where(arr>5)
arr

(array([5, 6, 7, 8], dtype=int64),)

## Search Sorted

There is function searchsorted() which implements binary search and returns index where the elements should be inserted such that search order is maintained.
Assumption is that searchsorted function is called on sorted array.

In [17]:
np.random.seed(45)
arr=np.random.randint(10,49,size=5)
print(arr)
arr.sort()
indx=np.searchsorted(arr,[18,45])
indx

[21 40 13 42 41]


array([1, 5], dtype=int64)

## Numpy Array Filtering

Getting some elements out of existing array and creating new array out of them is filtering.Filtering in numpy array can be done through boolean index list.Booolean index list is a list of boolean values corresponding to an index.

In [21]:
arr=np.arange(10,20,2)
print(arr)
x=arr>14 
print(x,arr[x])

[10 12 14 16 18]
[False False False  True  True] [16 18]
