### Numpy

1. Numpy is used to work with array.
2. The array object in Nupy is called ndarray.
3. We create ndarrray in Numpy by using array() function.

#### Implementation

In [4]:
import numpy as np
arr=np.array([1,2,3,4])
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


**type() is function that return type of object passed to it.**

*Note: To create array we can pass list,tuple or any array like object to array() method and it will be converted to ndarray.*

#### Examples

In [5]:
#passing list to array()
list1=[1,2,3,4]
arr=np.array(list1)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [12]:
#passing tuple to array()
tuple1=(1,2,3,4)
arr=np.array(tuple1)
print(arr)
print(type(arr))

[1 2 3 4]
<class 'numpy.ndarray'>


In [14]:
#pasisng set to array();set is a python data structure;It is mutable and contains dinstinct values.
set1={1,2,3,4}
arr=np.array(set1)
print(arr)
print(type(arr))

{1, 2, 3, 4}
<class 'numpy.ndarray'>


In [17]:
#passing dictionary to array();
dic={'Name':'Yogita','Company':'TCS'}
arr=np.array(dic)
print(arr)
print(type(arr))

{'Name': 'Yogita', 'Company': 'TCS'}
<class 'numpy.ndarray'>


### Dimensions In Array

1. A dimension in array is one level of array depth(nested arrays).
2. Nested array are arrays that have array as their elements.
3. **0-D array** : Each value in array is 0-D array or Scalar.For eg:25,[25]
4. **1-D array** : 1-D array or vector is mX1 or 1Xm type of array.Vector is collection of scalars.For eg:[2 3 4 5]
5. **Matrices** are collection of vectors.(2-D array)

### Implementation

In [31]:
scalar=np.array(25)
print(scalar,type(scalar),scalar.dtype)
print(f"Shape :{scalar.shape},dimension:{scalar.ndim}")

25 <class 'numpy.ndarray'> int32
Shape :(),dimension:0


In [28]:
scalar=np.array([25,34,45,67])
print(scalar,type(scalar),scalar.dtype)
print(f"Shape :{scalar.shape},dimension:{scalar.ndim}")

[25 34 45 67] <class 'numpy.ndarray'> int32
Shape :(4,),dimension:1


In [50]:
list1=[2,3,4,5]
list2=[3,4,5,8]
matrix=np.array([[list1,list2]])
print(matrix,type(matrix),matrix.dtype)
print(f"Shape :{matrix.shape},dimension:{matrix.ndim}")

[[[2 3 4 5]
  [3 4 5 8]]] <class 'numpy.ndarray'> int32
Shape :(1, 2, 4),dimension:3


In [42]:
list1=set([2,3,4,5])
list2=set([3,4,5,8])
matrix=np.array([list1,list2])
print(matrix,type(matrix),matrix.dtype)
print(f"Shape :{matrix.shape},dimension:{matrix.ndim}")

[{2, 3, 4, 5} {8, 3, 4, 5}] <class 'numpy.ndarray'> object
Shape :(2,),dimension:1


In [48]:
list1=[2,3,4,5]
list2=[3,4,5,8]
matrix=np.array([[list1,list2],[list2,list1]])
print(matrix,type(matrix),matrix.dtype)
print(f"Shape :{matrix.shape},dimension:{matrix.ndim}")

[[[2 3 4 5]
  [3 4 5 8]]

 [[3 4 5 8]
  [2 3 4 5]]] <class 'numpy.ndarray'> int32
Shape :(2, 2, 4),dimension:3


**ndim - Numpy attribute that return integer that tells us how many dimensions the array have.**

In [57]:
#we can pass ndmin argument to define number of dimensions we want for array.
arr=np.array([1,2,3,3],ndmin=5)
print(arr,arr.ndim)

[[[[[1 2 3 3]]]]] 5
