# Numpy Array Joining And Splitting

## Array Joining:concatenate()

Joining means putting content of two or more arrays in single array.In SQL we join two or more tables on the basis of key.
In Numpy, we join arrays by axes.We pass sequense of array to concatenate function along with axis, if axis is not mentioned explicity by default it is considered as zero.

* rows - axis=1
* column - axis=0

In [2]:
import numpy as np
arr1=np.array(range(1,6))
arr2=np.array(range(6,10))
print(arr1,arr2)
arr=np.concatenate((arr1,arr2))# by default axis is 0
print(arr)

[1 2 3 4 5] [6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [12]:
#2d array
arr1=np.arange(1,7).reshape(3,2)
arr2=np.full((3,2),8)
arr=np.concatenate((arr1,arr2))
arr3=np.concatenate((arr1,arr2),axis=1)
print("\nJoin array by column axis=0\n",arr)
print("\nJoin array by row axis=1\n",arr3)



Join array by column axis=0
 [[1 2]
 [3 4]
 [5 6]
 [8 8]
 [8 8]
 [8 8]]

Join array by row axis=1
 [[1 2 8 8]
 [3 4 8 8]
 [5 6 8 8]]


## Joining Arrays using Stack Function

It is same as concatenate function with the one distinction that stacking is done along new axis.by default axis is 0.

In [17]:
arr1=np.arange(1,7).reshape(3,2)
arr2=np.full((3,2),8)
arr=np.stack((arr1,arr2))
print(arr1,"\narr2:\n\n",arr2)
arr3=np.stack((arr1,arr2),axis=1)
print("\n\n",arr,"\n\nalong axis1:\n\n",arr3)

[[1 2]
 [3 4]
 [5 6]] 
arr2:

 [[8 8]
 [8 8]
 [8 8]]


 [[[1 2]
  [3 4]
  [5 6]]

 [[8 8]
  [8 8]
  [8 8]]] 

along axis1:

 [[[1 2]
  [8 8]]

 [[3 4]
  [8 8]]

 [[5 6]
  [8 8]]]


# hstack(),vstack(),dstack()

Numpy provides helper functions in order to stack along:
* horizontal/rows- hstack()
* column - vstack()
* height/depth - dstack()

In [18]:
hstack=np.hstack((arr1,arr2))
print(hstack)

[[1 2 8 8]
 [3 4 8 8]
 [5 6 8 8]]


In [19]:
vstack=np.vstack((arr1,arr2))
vstack

array([[1, 2],
       [3, 4],
       [5, 6],
       [8, 8],
       [8, 8],
       [8, 8]])

In [21]:
dstack=np.dstack((arr1,arr2))
dstack

array([[[1, 8],
        [2, 8]],

       [[3, 8],
        [4, 8]],

       [[5, 8],
        [6, 8]]])

# Splitting Array

Joining merges two or more arrays into one,where splitting breaks one array into multiple arrays.

* array_split() : We use it for splitting array ,we can pass array we want to split and the number of splits.If array has less element as required than it will adjust from end accordingly.



In [26]:
d=np.array_split(dstack,2)
d

[array([[[1, 8],
         [2, 8]],
 
        [[3, 8],
         [4, 8]]]),
 array([[[5, 8],
         [6, 8]]])]

In [28]:
d=np.array_split(dstack,3,axis=1)#similar to hsplit
d

[array([[[1, 8]],
 
        [[3, 8]],
 
        [[5, 8]]]),
 array([[[2, 8]],
 
        [[4, 8]],
 
        [[6, 8]]]),
 array([], shape=(3, 0, 2), dtype=int32)]

In [29]:
d=np.hsplit(dstack,2)
d

[array([[[1, 8]],
 
        [[3, 8]],
 
        [[5, 8]]]),
 array([[[2, 8]],
 
        [[4, 8]],
 
        [[6, 8]]])]

In [31]:
d=np.vsplit(dstack,3)
d

[array([[[1, 8],
         [2, 8]]]),
 array([[[3, 8],
         [4, 8]]]),
 array([[[5, 8],
         [6, 8]]])]

In [34]:
d=np.dsplit(dstack,2)
d

[array([[[1],
         [2]],
 
        [[3],
         [4]],
 
        [[5],
         [6]]]),
 array([[[8],
         [8]],
 
        [[8],
         [8]],
 
        [[8],
         [8]]])]