# Numpy random module

Random number does not mean a different number every time rather it is  the one that cannot be predicted logically.

Numpy provides random module to work with random numbers.

* random.randint() - to generate random integer number.We can provide size and start and end of the array.
* random.rand()- to generate float numbers.(between 0 and 1)

In [2]:
import numpy as np

In [19]:
arr=np.random.randint(100,200,5) #start=100,end=200,size=5
arr

array([153, 153, 170, 109, 181])

In [26]:
arr=np.random.rand(2) #size=2 #to generate number between 0 and 1 # sample from uniform distribution
arr

array([0.93881249, 0.26205444])

In [61]:
arr=np.random.randn(3,2)#return sample data from normal distribution
arr

array([[ 0.29647915,  1.05922242],
       [-0.66123715, -0.30023158],
       [-0.20145292,  0.34103942]])

Useful Functions from random module
* **choice() - Return elements randomly selected from passed array.**


* **shuffle() - Changes arrangement of elements in original array**

* **permutation() - return permutation of array/shuffled array.**

In [66]:
x=np.random.choice(arr.flatten(),3)
x

array([-0.66123715, -0.66123715,  1.05922242])

In [73]:
np.random.shuffle(arr)#occurs inplace
print(arr)#original array is 

[[-0.66123715 -0.30023158]
 [ 0.29647915  1.05922242]
 [-0.20145292  0.34103942]]


In [75]:
x=np.random.permutation(arr)
x

array([[ 0.29647915,  1.05922242],
       [-0.66123715, -0.30023158],
       [-0.20145292,  0.34103942]])

## Random Data Distribution

Data Distribution is the list of possible outcomes and how often each value occur.

### Random Distribution:
It is a set of random numbers that follow a certain probability density function.

### Probability Density Function:
A function that defines continuous probabilty;probability of all values in an array.

*We can generate random number based on defined probabilities using **choice** function of random module.It allows you to define probability for each value in array and it should be between 0 and 1.

In [78]:
x=np.random.choice([2,4,9,5],p=[0.4,0.2,0.3,0.1],size=(100))
x

array([4, 4, 2, 9, 2, 2, 4, 5, 9, 9, 2, 9, 5, 2, 4, 9, 4, 5, 9, 2, 9, 9,
       9, 9, 9, 2, 2, 4, 9, 4, 2, 2, 2, 4, 9, 9, 5, 4, 9, 9, 9, 5, 9, 2,
       4, 2, 9, 2, 2, 2, 4, 5, 4, 2, 9, 2, 4, 2, 9, 9, 5, 9, 9, 9, 2, 9,
       5, 9, 2, 9, 9, 4, 2, 2, 4, 2, 9, 9, 2, 4, 2, 9, 4, 4, 2, 9, 9, 9,
       2, 5, 2, 2, 2, 5, 2, 2, 2, 4, 5, 9])